### ISSUE TITLE
주소 목록에서 스크롤 내린 후 클릭했을때 버그가 있네요

### ISSUE THREAD

**Issue by jingyu91** [trilliwon/postcode#2]
1. 검색 후 스크롤을 내린다.
![image](https://user-images.githubusercontent.com/10904740/64059310-e66ef180-cbf4-11e9-95d9-f62a3e19137f.png)

2. 선택한다.

3. 스크롤이 올라가면서 다음 화면으로 이동하지 않음
![image](https://user-images.githubusercontent.com/10904740/64059321-18805380-cbf5-11e9-8b45-887cdbdcfba2.png)

ps 주소를 정확하게 클릭하지 않고, 주소텍스트를 살짝 빗겨서 클릭하면 제대로 동작하네요..

**Comment by trilliwon** [comment]
@jingyu91 

웹페이지는 제가 만든게 아니라서요. `http://postcode.map.daum.net/guide` 여기에 여쭤보심이...

**Comment by jingyu91** [comment]
네 감사합니다!
