### ISSUE TITLE
우편 번호 버튼을 누르고 난 후 웹 접속이 되지 않습니다.

### ISSUE THREAD

**Issue by aron1127** [trilliwon/postcode#3]
제목이 곧 내용입니다..
주소가 접속이 되지 않습니다. (서버 IP주소를 찾을 수 없다고 합니다.)
티스토리에도 댓글을 남겨두었습니다!

**Comment by trilliwon** [comment]
@aron1127 

안녕하세요, 커스텀 도메인에 문제가 있어서 접속이 안된거에요.
예제 앱에서 사용하는 URL 은 `https://trilliwon.github.io/postcode/` 이거에요.
이 URL 은 제 깃헙 Page 주소입니다.
서비스를 하시거나 테스트를 하실 때에는 `https://github.com/trilliwon/postcode` 이 레포를 포크 하신후에 예제의 URL 을 포크한 주소로 바꾼다음에 해보세요.

**Comment by aron1127** [comment]
해결했습니다! 포크까지 생각을 못했네요 ㅠ 정말 감사드립니다
